### ISSUE TITLE
Portfolio review- Cgleach

### ISSUE THREAD

**Issue by cgleach** [w201rdada/portfolio-susub31#5]
Overall I think it is an interesting concept, and I really like the way you integrate your data sources and references in throughout the peice.  The one thing I would say (and this absolutely may be me misinterpreting the assignment) was that this reads more like a write-up/summary of a project already completed, rather than a proposal.  I'm not sure to what extent this is an issue, but it may be worth confirming with Brooks.

Things to Consider:

1) HUD loves acronyms!! (Like absolutely loves them!)  However for a reader who isn't familiar with the various abbreviations I found the introduction a bit overwhelming.  I'm not sure all of the different terms actually need to be defined in HUD's terminology, and in turn this will keep the readers focused on what you're actually trying to say.

2) As mentioned above, the layout reads like an executive summary.  The middle portion contains multiple sections dedicated to explaining the different steps in working with the data; for the purposes of introducing a reader to a "big idea" I'm not quite sure that is all necessary.  There might be value in removing some of the content from this section.

Things to keep:

1) Aside from the acronyms, the introduction is really strong and presents a clear and focused narrative.  It is effective at identifying the issue and drawing the reader in!

**Comment by susub31** [comment]
@cgleach , thanks for the peer review and providing your feedback.  Please find below, my response to your suggestions.

1. Thanks for the suggestion, and I have included definitions of some key terms.
2. I have modified the content so that it focuses on a single idea, which is to build a tool that can be used by CoC staff to predict homeless counts.  The sections in the middle are now structured into that flow.
3. I have further included a few citations in the introduction to help support the idea.
