### ISSUE TITLE
Big Idea #1 Review - Rahul Kulkarni

### ISSUE THREAD

**Issue by rahul-kulkarni** [w201rdada/portfolio-susub31#6]
This is a commendable effort for social good. Amazed by the analysis you have done on this. 

Some Suggestions:

* The problem title is described as homelessness in US. When I first read it I was expecting a solution for homelessness, but the solution is addressing the counts, please consider stating the problem statement more clearly

* Instead of stating "Why don't we take a Data Science approach.." it would motivate the reader better if you state why we should and how data science will help. This could even be in the solution itself and not be described as part of the problem I think the last 4 lines in the problem statement can be restated

*It would help the reader to get and idea of  the  amount of tax dollars spent on homelessness before defining the hypotheses. 

* In terms of grant allocation - cost of shelter/food/etc can vary from state to state does the analysis take into account for the variability across the states

*I am sure you will be but describing how the prediction algorithm will work will be useful to know

**Comment by susub31** [comment]
@rahul-kulkarni , thanks for the peer review and your feedback on my big idea.  Please find my responses to your suggestions.

- I have re-structured the idea around how we can use ML tools to predict a more accurate homeless count, as a tool that could be used by CoC staff.

- I have modified the statement in the introduction paragraph so that it emphasizes the goal, which is to take a Data Science approach

- I have removed the grant allocation from my idea, and instead focused on only building a tool using Data Science / Machine Learning that CoC staff can use to get homeless counts.  As such, your suggestion in bullet 3 would not apply.
